### ISSUE TITLE
Disable button 

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsIncidentPortal#24]
On page 8: When form is blanc "versturen" button should be disabled /  gray.
Like the other pages.

![image](https://user-images.githubusercontent.com/46600362/94186872-80ac7200-fea7-11ea-870d-2ef0aa565178.png)

**Comment by yorickdewid** [comment]
Its not a bug, its a feature

**Comment by pnobbe** [comment]
Personal information is not _actually_ required.

**Comment by yorickdewid** [comment]
However, we now know that at least email is required

**Comment by pnobbe** [comment]
Fixed in #28
