### ISSUE TITLE
Form does not submit on iOS devices

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsIncidentPortal#25]
Form doesn't submit (page 8) in Safari.
Tested on latest IOS en MacOS in latest Safari version.

**Comment by pnobbe** [comment]
@yorickdewid and me were unable to find a solution, but we narrowed it down to a Safari-specific issue. It does not seem to like POST requests using the fetch API. Specifically it breaks in `Questions.vue`'s `handleNavigate` function:

```typescript
const response = fetch(`https://staging.fundermaps.com/api/incident-portal/submit`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: {}
      })
```

**Comment by yorickdewid** [comment]
@Solinx Will take a look
